% Copyright 2011 The Avalon Project Authors. All rights reserved.
% Use of this source code is governed by the Apache License 2.0
% that can be found in the LICENSE file.
% Steffen Grundmann, April 2011

function style()

% Show a string with rules and coding style conventions
"\nA few remarks on rules and style of this Octave code for the Avalon project. \n...
\n...
- All units are the basic SI units (m, s, N, etc.) and radians. If it makes sense to input parameters or output results\n...
  in knots, pints or ounces per square feet then convert that at the earliest/latest possible moment.\n...
  This pays back a thousand times and might save the project from catastrophic failure.\n...
- Functions are preferred, scripts are to b used only where necessary (pollution of symbol space).\n...
- Functions shall have  a documenting comment after the function signature definition explaining all parameters.\n...
- The % sign is used for comments preferably.\n...
- Strings should use double quotes. \n...
- Outside of matrix definitions the C++ operator spacing conventions shall be followed. \n  Powers ( x^2 ) are written compact.\n ...
"
endfunction