% Copyright 2011 The Avalon Project Authors. All rights reserved.
% Use of this source code is governed by the Apache License 2.0
% that can be found in the LICENSE file.
% Steffen Grundmann, April 2011

function result = test_all()
% function result = test_all()

result = angle_of_attack_test() & ...
         force_hull_test() & ...
         forces_test() & ...
         rotation_matrix_test() & ...
         derivatives_test() & ...
         force_of_test() & ...
         pack_state_script_test() & ...
         tangential_speed_test();

endfunction