#! /bin/sh
### BEGIN INIT INFO
# Provides:          buswatch_reboot
# Required-Start:    $remote_fs $syslog imucfg lbus
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start buswatch (reboot) on lbus
# Description:       Start buswatch (reboot) on lbus
### END INIT INFO

# Author: Luuk van Dijk <lvd@google.com>

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
DESC="buswatch (reboot)"
NAME=buswatch_reboot
SCRIPTNAME=/etc/init.d/$NAME

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

err=""
for p in plug buswatch sms; do
    which $p >/dev/null 2>&1 || err="$err $p"
done
[ "$err" = "" ] || { log_failure_msg "Missing binaries: $err" ; exit 0; }


#
# Function that starts the daemon/service
#
do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
        echo '$stats' | plug -f xxx /var/run/lbus | grep -q $NAME && return 1

	# don't background, be precious
	# TODO: in runlevel 3 also watch for helmsman_st: and helm:
	plug -pon $NAME /var/run/lbus -- `which buswatch` -t 600 DIE compass: gps: imu: wind: status_left: status_right: status_sail: 2> /dev/null
	# if we exit, the lbus was dead or will be dead: sms and reboot
	for p in `cat /etc/smsphonenr`; do
	    sms send $p "$(date) lbus watch died, rebooting"
	done
	reboot
}

#
# Function that stops the daemon/service
#
do_stop()
{
    echo Buswatch reboot can not be stopped
    return 2
}

do_status()
{
    echo '$stats' | plug -f xxx /var/run/lbus | grep $NAME || log_warning_msg "$NAME not plugged in."
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  status)
	do_status
       ;;
  restart|force-reload)
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
	  	# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
